services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    # add your own data here
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    networks:
      - default

  web:
    build:
      context: ./frontend
    container_name: react_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - default

  api:
    build: ./api
    container_name: django_container
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - /path_to_your_local_html_files:/app/movie_htmls
    depends_on:
      - db
    environment:
      DB_NAME: 
      DB_USER: 
      DB_PASSWORD: 
      DB_HOST: 
      DB_PORT: 
      DJANGO_SETTINGS_MODULE: backend.settings
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    shm_size: "2gb"

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
