services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    # add your own data here
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    networks:
      - default

  #rabbitmq:
  #  image: rabbitmq:3-management
  #  container_name: rabbitmq_container
  #  ports:
  #    - "5672:5672"
  #    - "15672:15672"
  #  networks:
  #    - default

  web:
    build: ./frontend
    container_name: react_container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    networks:
      - default

  api:
    build: ./api
    container_name: django_container
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - db
    environment:
      DB_NAME: yidio_db
      DB_USER: main_yidio
      DB_PASSWORD: 2526
      DB_HOST: db
      DB_PORT: 3306
      DJANGO_SETTINGS_MODULE: backend.settings
    networks:
      - default

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium_chrome
    ports:
      - "4444:4444"
    shm_size: "2gb"

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
