# Generated by Django 3.2.25 on 2025-08-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=512)),
                ('classification', models.CharField(blank=True, default='NR', max_length=10, null=True)),
                ('year', models.IntegerField()),
                ('length', models.CharField(blank=True, max_length=20, null=True)),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField()),
            ],
        ),
    ]
