# Generated by Django 3.2.25 on 2025-08-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yidio_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'year', 'length')},
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
