# Generated by Django 3.2.25 on 2025-08-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yidio_scraper', '0002_auto_20250805_2301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='YidioMovie',
        ),
        migrations.AlterModelTable(
            name='yidiomovie',
            table='yidio_scraper_movie',
        ),
    ]
